const mongoose = require('mongoose');

const materialSchema = new mongoose.Schema({
    _id: mongoose.Schema.Types.ObjectId,
    originalTitle: { type: String, required: false,default: "Im a default title"},
    ownTitle: { type: String, required: false},
    listTitle: { type: String, required: false},
    src: { type: String, required: false, default:"https://www.unesale.com/ProductImages/Large/notfound.png"},
    codMaterial: { type: String, required: false},
    codProgram: { type: String, required: false},
    materialType: { type: String, required: false},
    classification: { type: String, required: false},
    numClassification: { type: String, required: false},
    broadcastPrice: { type: String, required: false},
    broadcastCredit: { type: String, required: false},
    mainActors: { type: [], required: false},
    secondaryActors: { type: [], required: false},
    validity: { type: [], required: false},
    typeOfCannedMaterial: { type: String, required: false},
    costCenter: { type: String, required: false},
    numCenter: { type: String, required: false},
    genre: { type: String, required: false},
    director: { type: [], required:false},
    allMusicalThemes: { type: [], required:false},
    hoursMaterial: { type: String, default: "01"},
    minutesMaterial: { type: String, default: "30"},
    minTimeTheme: { type: String, default: "04" },
    secTimeTheme: { type: String, default: "00" },
    checkedSignals: { type: [], required: false},
    numChapters: { type: String, default: 1},
    updateDate: { type: Date, default: Date.now },
    uploadDate: { type: String, required: false},
    supportsRelated: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Support', required: false}],
    contract: { type: mongoose.Schema.Types.ObjectId, ref: 'Contract', required: false },
    videoCutting: { type: [], required: false},
    cutAllChapters: { type: Boolean, default: false},
    rankChapters: [{ from: String, to: String, rankCutting: []}],
    individualEntryOfChapters: [{ chapter: String, chapterCutting: []}],
    productionCompany: { type: String, default: 'Produccion Nacional'},
    netDuration: { type: String, default: 'Produccion Nacional'},
    status: { type: Boolean, default: true},
    canned: { type: Boolean, required: false},
    unitPrice: { type: String, required: false},
    providerCode: { type: String, required: false},
    provider: { type: String, required: false},
    totalPass: { type: String, required: false},
    scheduledTimes: { type: [], required: false},
    arrivalDate: { type: String, required: false},
    emissions: { type: [], default: ['No emitido']},
    systemCode: { type: String, required: false},
    newNetDuration: { type: String, default: ""}
},{
    collection: 'materials'
});

module.exports = mongoose.model('Material', materialSchema);